/**
 * Budgetear API
 * Minimal API for storing and retrieving budget data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Purchases { 
    /**
     * the cost of the item
     */
    cost?: number;
    /**
     * Name of product
     */
    name?: string;
    /**
     * Produkt type
     */
    type?: string;
    /**
     * produkt category
     */
    category?: string;
}

