/**
 * Budgetear API
 * Minimal API for storing and retrieving budget data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Spendings { 
    /**
     * the cost of the item
     */
    cost?: number;
    name?: string;
    type?: string;
    category?: string;
}

